### ISSUE TITLE
Where is the function "transfer_attack"? Please!

### ISSUE THREAD

**Issue by igeng** [Kaminyou/PGD-Implemented-Adversarial-attack-on-CIFAR10#1]
Hello! Appreciate for great code about adversarial attacks. When I study your code, I found that I don't know what the function "transfer_attack" is in the transferability.py. Could you please tell me how can I implement this key function? Thx!

**Comment by Kaminyou** [comment]
@igeng Sorry I did not tidy up these codes well since this is my early work. I did find my original implementation and amended it. Please see the latest version (latest commit).
If there are still other issues, please let me know.
